"use client";
import { useMemo, useState } from "react";
import { cognitiveLevels, type CognitiveLevel } from "@/lib/assessment/cognitive-levels";
import { getAssessmentStructure } from "@/lib/assessment/structure-policy";
import type { AssessmentGrade, AssessmentSubject } from "@/lib/assessment/scoring-policy";

type DraftItem = { id: string; title: string; level: CognitiveLevel; points: number; instruction: string };
const subjects: { value: AssessmentSubject; label: string }[] = [{ value: "history", label: "التاريخ" }, { value: "geography", label: "الجغرافيا" }, { value: "civic-education", label: "التربية المدنية" }];
const grades: { value: AssessmentGrade; label: string }[] = [{ value: "1am", label: "الأولى متوسط" }, { value: "2am", label: "الثانية متوسط" }, { value: "3am", label: "الثالثة متوسط" }, { value: "4am", label: "الرابعة متوسط" }];
const createItem = (): DraftItem => ({ id: crypto.randomUUID(), title: "وضعية بسيطة", level: "knowledge", points: 1, instruction: "" });

export function AssessmentBuilder() {
  const [grade, setGrade] = useState<AssessmentGrade>("4am"); const [subject, setSubject] = useState<AssessmentSubject>("history"); const [title, setTitle] = useState("التقويم التحصيلي"); const [items, setItems] = useState<DraftItem[]>([createItem()]); const [saveState, setSaveState] = useState("");
  const structure = useMemo(() => getAssessmentStructure(grade, subject), [grade, subject]); const assignedPoints = items.reduce((sum, item) => sum + (Number(item.points) || 0), 0); const remaining = structure.totalPoints - assignedPoints;
  function updateItem(id: string, patch: Partial<DraftItem>) { setItems((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item)); }
  async function saveDraft() { if (remaining !== 0 || items.some((item) => !item.instruction.trim())) { setSaveState("أكمل التعليمات واضبط مجموع النقاط قبل الحفظ."); return; } setSaveState("جارٍ الحفظ…"); const response = await fetch("/api/assessments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ grade, subject, title, durationMinutes: grade === "4am" && subject !== "civic-education" ? 90 : 60, items }) }); const data = await response.json(); if (response.ok) { window.location.assign(`/assessment/${data.id}`); return; } setSaveState(data.error ?? "تعذر الحفظ."); }
  return <div className="space-y-6"><div className="grid gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2"><label className="text-sm sm:col-span-2">عنوان التقويم التحصيلي<input value={title} onChange={(event) => setTitle(event.target.value)} className="mt-1 w-full rounded-md border border-slate-300 p-2" /></label><label className="text-sm">المستوى<select value={grade} onChange={(event) => setGrade(event.target.value as AssessmentGrade)} className="mt-1 w-full rounded-md border border-slate-300 p-2">{grades.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="text-sm">المادة<select value={subject} onChange={(event) => setSubject(event.target.value as AssessmentSubject)} className="mt-1 w-full rounded-md border border-slate-300 p-2">{subjects.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><div className="sm:col-span-2 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-950"><b>المجموع المستهدف: {structure.totalPoints} نقطة.</b> {structure.official && <span> البنية المرجعية: {structure.parts.map((part) => `${part.label} ${part.points}ن`).join(" + ")}.</span>}</div></div>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">وضعيات وعناصر التقويم</h2><p className="text-sm text-slate-600">اختر مستوى بلوم، واستعمل فعلاً دالاً في التعليمة.</p></div><button onClick={() => setItems((current) => [...current, createItem()])} className="rounded-lg bg-slate-800 px-3 py-2 text-sm font-semibold text-white">إضافة وضعية</button></div><div className="mt-5 space-y-4">{items.map((item, index) => <article key={item.id} className="rounded-lg border border-slate-200 p-4"><div className="grid gap-3 sm:grid-cols-[1fr_170px_100px]"><label className="text-sm">العنوان<input value={item.title} onChange={(event) => updateItem(item.id, { title: event.target.value })} className="mt-1 w-full rounded-md border border-slate-300 p-2" /></label><label className="text-sm">المستوى المعرفي<select value={item.level} onChange={(event) => updateItem(item.id, { level: event.target.value as CognitiveLevel })} className="mt-1 w-full rounded-md border border-slate-300 p-2">{Object.entries(cognitiveLevels).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select></label><label className="text-sm">النقاط<input type="number" min="0.5" step="0.5" value={item.points} onChange={(event) => updateItem(item.id, { points: Number(event.target.value) })} className="mt-1 w-full rounded-md border border-slate-300 p-2" /></label></div><p className="mt-3 text-xs text-slate-500">أفعال مقترحة: {cognitiveLevels[item.level].verbs.join("، ")}</p><label className="mt-3 block text-sm">التعليمة<textarea value={item.instruction} onChange={(event) => updateItem(item.id, { instruction: event.target.value })} rows={3} placeholder={`مثال: ${cognitiveLevels[item.level].verbs[0]} …`} className="mt-1 w-full rounded-md border border-slate-300 p-2" /></label><div className="mt-3 flex justify-between"><span className="text-xs text-slate-500">الوضعية {index + 1}</span><button onClick={() => setItems((current) => current.filter((entry) => entry.id !== item.id))} disabled={items.length === 1} className="text-xs text-red-700 disabled:opacity-40">حذف</button></div></article>)}</div><div className={`mt-5 rounded-lg p-4 text-sm ${remaining === 0 ? "bg-emerald-50 text-emerald-900" : "bg-amber-50 text-amber-900"}`}><b>النقاط المسندة: {assignedPoints} / {structure.totalPoints}</b><br />{remaining === 0 ? "التوزيع يطابق المجموع المستهدف." : remaining > 0 ? `يتبقى ${remaining} نقطة للتوزيع.` : `تم تجاوز المجموع بـ ${Math.abs(remaining)} نقطة.`}</div><div className="mt-4 flex flex-wrap items-center gap-3"><button onClick={saveDraft} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">حفظ المسودة</button>{saveState && <span className="text-sm text-slate-700">{saveState}</span>}</div></section></div>;
}
