import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { getReviewedReferencePack } from "@/packages/domain/reference-packs/registry";
import { getHistoryGeographyAllocation } from "@/lib/assessment/scoring-policy";
import { generateJson } from "@/lib/ai/openai-responses";
const levels=["knowledge","comprehension","application","analysis","creation","evaluation"] as const;
const schema=z.object({grade:z.enum(["1am","2am","3am","4am"]),domain:z.enum(["social-studies","civic-education"])});
export async function POST(request:Request){const p=schema.safeParse(await request.json());if(!p.success)return NextResponse.json({error:"المستوى أو المادة غير صالح."},{status:400});const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:"غير مصرح."},{status:401});const packs=p.data.domain==="social-studies"?[...getReviewedReferencePack("history",p.data.grade),...getReviewedReferencePack("geography",p.data.grade)]:getReviewedReferencePack("civic-education",p.data.grade);if(!packs.length)return NextResponse.json({error:"لا توجد حزمة مرجعية مفعلة."},{status:409});const allocations=p.data.domain==="social-studies"?getHistoryGeographyAllocation(p.data.grade):[{subject:"civic-education",points:20}];const sources=packs.map(x=>({subject:x.subject,title:x.title,competence:x.terminalCompetence,resources:x.resources,page:x.citation.page}));const draftSchema=z.object({items:z.array(z.object({subject:z.enum(["history","geography","civic-education"]),title:z.string().min(3),level:z.enum(levels),points:z.number().positive(),instruction:z.string().min(3),kind:z.enum(["simple","integrative"]),context:z.string().optional(),sources:z.array(z.string()).optional(),expectedOutput:z.string().optional()})).min(1)});
try{const format=`Return exactly this JSON shape and no other keys: {\"items\":[{\"subject\":\"history|geography|civic-education\",\"title\":\"Arabic title\",\"level\":\"knowledge|comprehension|application|analysis|creation|evaluation\",\"points\":number,\"instruction\":\"Arabic student instruction\"}]}. Do not use markdown. Do not add explanations outside JSON. For social-studies, include both history and geography items and respect allocations exactly. Simple items must have kind simple and no context or sources. Only one integrative item per subject may contain context, sources, and expectedOutput.`;const draft=await generateJson<unknown>(`${format} Use only provided curriculum sources. Do not invent official competencies or facts.`, `Return a JSON object only. ${format} Curriculum context: ${JSON.stringify({grade:p.data.grade,domain:p.data.domain,allocations,sources})}`);const checked=draftSchema.safeParse(draft);if(!checked.success){console.error("Nibras AI invalid assessment draft:",JSON.stringify(draft).slice(0,3000));return NextResponse.json({error:"أعاد النموذج مسودة غير منظمة. أعد المحاولة أو غيّر النموذج."},{status:422});}return NextResponse.json({draft:checked.data});}catch(error){const message=error instanceof Error?error.message:"Unknown AI error";console.error("Nibras AI assessment generation failed:",message);return NextResponse.json({error:"تعذر توليد المسودة. تحقق من مفتاح OpenAI وصلاحية Responses.",debug:process.env.NODE_ENV==="development"?message:undefined},{status:502});}}
