import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getCurrentWorkspaceId } from "@/lib/workspace/current-workspace";
import Link from "next/link";
import type { Route } from "next";
import { ResourceReview } from "@/components/inspector/resource-review";
import { ContentPlanLink } from "@/components/planner/content-plan-link";
export default async function ContentDetailPage({params}:{params:Promise<{contentId:string}>}){const {contentId}=await params;const supabase=await createClient();const workspaceId=await getCurrentWorkspaceId();const {data:content}=await supabase.from("content_items").select("title,body,content_type,status,plan_item_id").eq("id",contentId).eq("organization_id",workspaceId).single();if(!content)notFound();
  const { data: planItems } = await supabase.from("plan_items").select("id,title").eq("organization_id",workspaceId).order("sort_order");const body=content.body as {targetedCompetence:string;evidenceOfLearning:string;activity:{instruction:string;durationMinutes:number;expectedProduct:string};formativeAssessment:string;source:{documentTitle:string;page:number;excerpt:string}};return <section><p className="text-sm font-semibold text-emerald-700">Content Studio · {content.content_type}</p><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-bold">{content.title}</h1><Link href={`/studio/${contentId}/edit` as Route} className="rounded-lg bg-slate-800 px-4 py-2 text-sm font-semibold text-white">تعديل المورد</Link></div><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_320px]"><article className="max-w-4xl rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">الكفاءة المستهدفة</h2><p>{body.targetedCompetence}</p><h2 className="mt-5 font-bold">دليل الإتقان</h2><p>{body.evidenceOfLearning}</p><h2 className="mt-5 font-bold">النشاط — {body.activity.durationMinutes} دقيقة</h2><p>{body.activity.instruction}</p><p className="mt-2 text-sm text-slate-600">المنتج: {body.activity.expectedProduct}</p><h2 className="mt-5 font-bold">التقويم التكويني</h2><p>{body.formativeAssessment}</p><blockquote className="mt-5 rounded-lg border-r-4 border-emerald-600 bg-emerald-50 p-4 text-sm"><b>{body.source.documentTitle}، ص {body.source.page}</b><br/>«{body.source.excerpt}»</blockquote></article><div><ResourceReview body={body}/><ContentPlanLink contentId={contentId} items={planItems??[]} currentPlanItemId={content.plan_item_id}/></div></div></section>;}
