import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getCurrentWorkspaceId } from "@/lib/workspace/current-workspace";

export default async function AnalyticsRunPage({ params }: { params: Promise<{ runId: string }> }) {
  const { runId } = await params; const supabase = await createClient(); const workspaceId = await getCurrentWorkspaceId();
  const { data: run } = await supabase.from("assessment_runs").select("id,conducted_on,participant_count,summative_assessments(title),aggregated_results(criterion_label,assessed_count,mastered_count,common_error),interventions(id,title,intervention_type,status,activity,duration_minutes,success_indicator)").eq("id", runId).eq("organization_id", workspaceId).single();
  if (!run) notFound(); const assessment = Array.isArray(run.summative_assessments) ? run.summative_assessments[0] : run.summative_assessments;
  return <section><p className="text-sm font-semibold text-emerald-700">Teaching Analytics</p><h1 className="mt-1 text-3xl font-bold">نتيجة التحليل</h1><p className="mt-2 text-slate-600">{assessment?.title ?? "التقويم التحصيلي"} · تاريخ التنفيذ: {run.conducted_on} · المشاركون: {run.participant_count ?? "—"}</p><div className="mt-7 grid gap-5 lg:grid-cols-2"><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">الإتقان حسب المعيار</h2><div className="mt-4 space-y-3">{(run.aggregated_results ?? []).map((result) => { const rate = Math.round((result.mastered_count / result.assessed_count) * 100); return <div key={result.criterion_label} className="rounded-lg border border-slate-100 p-3"><div className="flex justify-between gap-4"><b>{result.criterion_label}</b><span className={rate < 50 ? "font-bold text-red-700" : rate < 75 ? "font-bold text-amber-700" : "font-bold text-emerald-700"}>{rate}%</span></div><p className="mt-1 text-sm text-slate-600">{result.mastered_count} من {result.assessed_count} متحكمين</p>{result.common_error && <p className="mt-2 text-sm text-red-800">الخطأ المتكرر: {result.common_error}</p>}</div>; })}</div></article><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">خطة العلاج والإثراء</h2><div className="mt-4 space-y-3">{(run.interventions ?? []).map((intervention) => <div key={intervention.id} className="rounded-lg border-r-4 border-emerald-600 bg-emerald-50 p-3"><div className="flex justify-between gap-3"><b>{intervention.title}</b><span className="text-xs text-emerald-800">{intervention.intervention_type === "remediation" ? "علاج" : "إثراء"}</span></div><p className="mt-2 text-sm">{intervention.activity}</p><p className="mt-2 text-xs text-slate-600">{intervention.duration_minutes} دقيقة · مؤشر النجاح: {intervention.success_indicator}</p></div>)}{!run.interventions?.length && <p className="text-sm text-slate-600">لا توجد تدخلات مطلوبة حالياً.</p>}</div></article></div></section>;
}
