import { notFound } from "next/navigation";
import Link from "next/link";
import type { Route } from "next";
import { createClient } from "@/lib/supabase/server";
import { getCurrentWorkspaceId } from "@/lib/workspace/current-workspace";
import { AssessmentPrintDocument } from "@/components/assessment/assessment-print-document";
import { PrintButton } from "@/components/assessment/print-button";
import { reviewSummativeAssessment } from "@/lib/inspector/review";
import { getAssessmentStructure } from "@/lib/assessment/structure-policy";
export default async function AssessmentDetailPage({ params }: { params: Promise<{ assessmentId: string }> }) { const { assessmentId } = await params; const supabase = await createClient(); const workspaceId = await getCurrentWorkspaceId(); const { data: assessment } = await supabase.from("summative_assessments").select("id,title,duration_minutes,total_points,grade_levels(name_ar),subjects(name_ar),summative_assessment_items(instruction,points,cognitive_level,sort_order,expected_answer)").eq("id", assessmentId).eq("organization_id", workspaceId).single(); if (!assessment) notFound(); const subjectCode = assessment.subjects?.[0]?.name_ar === "التاريخ" ? "history" : assessment.subjects?.[0]?.name_ar === "الجغرافيا" ? "geography" : "civic-education"; const gradeCode = assessment.grade_levels?.[0]?.name_ar === "الأولى متوسط" ? "1am" : assessment.grade_levels?.[0]?.name_ar === "الثانية متوسط" ? "2am" : assessment.grade_levels?.[0]?.name_ar === "الثالثة متوسط" ? "3am" : "4am"; const review=reviewSummativeAssessment({totalPoints:assessment.total_points,expectedPoints:getAssessmentStructure(gradeCode,subjectCode).totalPoints,items:(assessment.summative_assessment_items??[]).map(item=>({instruction:item.instruction,points:item.points,cognitiveLevel:item.cognitive_level}))}); return <section><div className="no-print flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-emerald-700">Assessment Bank</p><h1 className="mt-1 text-3xl font-bold">{assessment.title}</h1></div><div className="flex gap-2"><Link href={"/assessment" as Route} className="rounded-lg border border-slate-300 px-4 py-2 text-sm">العودة إلى التقويمات</Link><PrintButton /></div></div><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_300px]"><AssessmentPrintDocument assessment={assessment}/><aside className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><b>مراجعة التقويم</b><b className="text-emerald-700">{review.score}/100</b></div>{review.findings.map(f=><p key={f.message} className={f.level==="strength"?"mt-3 text-sm text-emerald-800":"mt-3 text-sm text-amber-800"}>{f.level==="strength"?"✓":"!"} {f.message}</p>)}</aside></div></section>; }
