"use client";
import { useState } from "react";
type StructuredResult = { id: string; title: string; term: number; terminalCompetence: string; resources: string[]; citation: { documentTitle: string; versionLabel: string; page: number; excerpt: string } };
type CorpusResult = { subject: string; grade: string; title: string; versionLabel: string; checksumSha256: string; page: number; excerpt: string };
const subjects = [{ value: "", label: "كل المواد" }, { value: "history", label: "التاريخ" }, { value: "geography", label: "الجغرافيا" }, { value: "civic-education", label: "التربية المدنية" }];
const grades = [{ value: "", label: "كل المستويات" }, { value: "1am", label: "الأولى متوسط" }, { value: "2am", label: "الثانية متوسط" }, { value: "3am", label: "الثالثة متوسط" }, { value: "4am", label: "الرابعة متوسط" }];

export function ReferenceSearch() {
  const [query, setQuery] = useState("الآثار ونمط معيشة إنسان ما قبل التاريخ"); const [subject, setSubject] = useState(""); const [grade, setGrade] = useState(""); const [structured, setStructured] = useState<StructuredResult[]>([]); const [corpus, setCorpus] = useState<CorpusResult[]>([]); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function search(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const params = new URLSearchParams({ query }); if (subject) params.set("subject", subject); if (grade) params.set("grade", grade); const response = await fetch(`/api/knowledge/search?${params}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setStructured(data.structured); setCorpus(data.corpus); setNotice(data.reviewNotice); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر تنفيذ البحث."); } finally { setLoading(false); } }
  return <div><form onSubmit={search} className="grid gap-3 sm:grid-cols-[1fr_170px_170px_auto]"><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 rounded-lg border border-slate-300 bg-white px-4 py-3 sm:col-span-1" placeholder="اكتب كفاءة أو مقطعاً أو مورداً…" /><select value={subject} onChange={(event) => setSubject(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-3">{subjects.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select value={grade} onChange={(event) => setGrade(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-3">{grades.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><button className="rounded-lg bg-emerald-700 px-5 py-3 font-semibold text-white disabled:opacity-60" disabled={loading}>{loading ? "جارٍ البحث…" : "بحث موثق"}</button></form>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-6 space-y-4">{structured.map((result) => <article key={result.id} className="rounded-xl border border-emerald-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-bold">{result.title}</h2><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800">حزمة مرجعية مراجعة · الفصل {result.term}</span></div><p className="mt-3 text-sm text-slate-700"><b>الكفاءة:</b> {result.terminalCompetence}</p><p className="mt-2 text-sm text-slate-600"><b>الموارد:</b> {result.resources.join("، ")}</p><blockquote className="mt-4 rounded-lg border-r-4 border-emerald-600 bg-emerald-50 p-3 text-sm text-emerald-950"><b>مصدر موثق — {result.citation.documentTitle}، ص {result.citation.page}:</b><br />«{result.citation.excerpt}»</blockquote></article>)}{corpus.map((result, index) => <article key={`${result.checksumSha256}-${result.page}-${index}`} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-base font-bold">{result.title}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-700">{result.subject} · {result.grade} · ص {result.page}</span></div><blockquote className="mt-3 rounded-lg border-r-4 border-slate-500 bg-slate-50 p-3 text-sm text-slate-800">«{result.excerpt}»</blockquote><p className="mt-2 text-xs text-slate-500">الإصدار: {result.versionLabel} · بصمة الوثيقة: {result.checksumSha256.slice(0, 12)}…</p></article>)}{!loading && !error && structured.length === 0 && corpus.length === 0 && <p className="rounded-lg border border-dashed border-slate-300 p-5 text-sm text-slate-600">ابحث في المخططات السنوية المعتمدة حسب المادة والمستوى.</p>}</div>{notice && (structured.length > 0 || corpus.length > 0) && <p className="mt-4 text-xs text-amber-800">{notice}</p>}</div>;
}
