import type { ReferenceSegment } from "@/packages/domain/reference-packs/types";
const title = "المخططات السنوية 2022 تربية مدنية السنة الأولى متوسط";
const versionLabel = "المخططات السنوية المعتمدة 2022";
const checksumSha256 = "6e717d2f14b22137058198d9bff2b14ef44d39d3edb043ddf69414f598346b51";
const comprehensiveCompetence = "معرفة الطابع الجمهوري للدولة الجزائرية والتفاعل الإيجابي مع المحيط على أساس ممارسة الحق وأداء الواجب.";
export const civicEducationGrade1Reference: ReferenceSegment[] = [
  { id: "civic-education-1am-term-1-community-life", subject: "civic-education", grade: "1am", term: 1, title: "الحياة الجماعية", comprehensiveCompetence, terminalCompetence: "يتفاعل بشكل إيجابي في محيطه من خلال تقبله للتنوع الثقافي ونبذه للتفرقة والتمييز العنصري.", resources: ["التنوع الثقافي", "التفرقة والتمييز العنصري", "الحوار", "تقبل الآخر"], citation: { documentTitle: title, versionLabel, page: 5, checksumSha256, excerpt: "يتفاعل بشكل إيجابي في محيطه من خلال تقبله للتنوع الثقافي ونبذه للتفرقة والميز العنصري." } },
  { id: "civic-education-1am-term-2-civic-life", subject: "civic-education", grade: "1am", term: 2, title: "الحياة المدنية", comprehensiveCompetence, terminalCompetence: "يمارس حقوقه وواجباته انطلاقا مما تفرضه وتيرة التمدرس في المؤسسة التعليمية من نظام ومسؤولية تجاه الذات والغير.", resources: ["الحقوق والواجبات", "القانون الأساسي للمؤسسة", "النظام الداخلي للمؤسسة", "الحياة المدرسية"], citation: { documentTitle: title, versionLabel, page: 6, checksumSha256, excerpt: "يمارس حقوقه وواجباته انطلاقا مما تفرضه وتيرة التمدرس في المؤسسة التعليمية من نظام ومسؤولية تجاه الذات والغير." } },
  { id: "civic-education-1am-term-3-democratic-life", subject: "civic-education", grade: "1am", term: 3, title: "الحياة الديمقراطية ومؤسسات الجمهورية", comprehensiveCompetence, terminalCompetence: "ينطلق من مفهوم الدولة الجزائرية كجمهورية ديمقراطية شعبية لتأكيد تمسكه بترقية العلاقات الاجتماعية في إطار المؤسسات.", resources: ["الدولة الجزائرية", "النظام الجمهوري", "سلطات الدولة الجزائرية"], citation: { documentTitle: title, versionLabel, page: 7, checksumSha256, excerpt: "ينطلق من مفهوم الدولة الجزائرية كجمهورية ديمقراطية شعبية لتأكيد تمسكه بترقية العلاقات الاجتماعية في اطار المؤسسات." } }
];
