import type { ReferenceSegment } from "@/packages/domain/reference-packs/types";
const title = "المخططات السنوية 2022 تربية مدنية السنة الثانية متوسط";
const versionLabel = "المخططات السنوية المعتمدة 2022";
const checksumSha256 = "5e01743f6054b915ddc268ac0fe3aa7d1ee87c6114a54f4c1b0a9e4f6cac4860";
const comprehensiveCompetence = "ممارسة حرية التعبير من خلال المشاركة في حوارات كأسلوب حضاري في حل المشاكل داخل الأطر النظامية، والتفاعل الإيجابي مع المحيط على أساس ممارسة الحق وأداء الواجب.";
export const civicEducationGrade2Reference: ReferenceSegment[] = [
  { id: "civic-education-2am-term-1-community-life", subject: "civic-education", grade: "2am", term: 1, title: "الحياة الجماعية", comprehensiveCompetence, terminalCompetence: "يمارس الحوار البناء باعتباره سلوكا حضاريا وأساسيا في الحياة الجماعية لحل المشاكل داخل الأطر النظامية.", resources: ["الحوار البناء", "التنظيمات الاجتماعية والثقافية والرياضية", "القانون الأساسي", "النظام الداخلي للجمعية"], citation: { documentTitle: title, versionLabel, page: 6, checksumSha256, excerpt: "يمارس الحـوار البناء باعتباره سلوكا حضاريا وأساسيـا في الحيـاة الجماعية لحلّ المشاكل داخل الأطر النظامية." } },
  { id: "civic-education-2am-term-2-civic-life", subject: "civic-education", grade: "2am", term: 2, title: "الحياة المدنية", comprehensiveCompetence, terminalCompetence: "ينطلق من الحق في الإعلام للتعبير عن تمسكه بحرية التعبير واحترامه لحرية الآخرين.", resources: ["وسائل الإعلام", "شبكات التواصل الاجتماعي", "حرية التعبير", "احترام الحياة الخاصة"], citation: { documentTitle: title, versionLabel, page: 7, checksumSha256, excerpt: "ينطلق من الحـقّ في الإعلام للتعـبير عـن تمسّكه بحرّية التعبير، واحترامـه لحرّيـة الآخرين." } },
  { id: "civic-education-2am-term-3-democratic-life", subject: "civic-education", grade: "2am", term: 3, title: "الحياة الديمقراطية ومؤسسات الجمهورية", comprehensiveCompetence, terminalCompetence: "بعد التعرف على قواعد سير المجالس المنتخبة يؤكد تمسكه بالمبادئ الديمقراطية في تسيير شؤون المواطنين.", resources: ["المجالس المنتخبة", "الانتخابات الولائية والوطنية", "مهام المجالس المنتخبة", "علاقة المواطن بالمجالس المنتخبة"], citation: { documentTitle: title, versionLabel, page: 8, checksumSha256, excerpt: "بعد التعرف على قواعد سير المجالس المنتخبة يؤكّد تمسّكه بالمبادئ الديمقراطية في تسيير شؤون المواطنين." } }
];
