import type { ReferenceSegment } from "@/packages/domain/reference-packs/types";
const title = "المخططات السنوية 2022 تاريخ السنة الثانية متوسط";
const versionLabel = "المخططات السنوية المعتمدة 2022";
const checksumSha256 = "fae09fa82baefaaf97d87db38c751cb9d7e63fe536640b85b7a3d63d5e2f95c8";
const comprehensiveCompetence = "ربط العلاقة بين الفتوحات الإسلامية ومجالات التأثير الحضاري للإسلام في العالم، بعد الكشف عن المبادئ التي قام عليها المجتمع الإسلامي الجديد.";
export const historyGrade2Reference: ReferenceSegment[] = [
  { id: "history-2am-term-1-historical-documents", subject: "history", grade: "2am", term: 1, title: "الوثائق التاريخية", comprehensiveCompetence, terminalCompetence: "يدرس المتعلم الوثيقة التاريخية من حيث طبيعتها ومصدرها ونوعها.", resources: ["الوثيقة التاريخية", "الاتفاقيات والمعاهدات التاريخية", "صحيفة المدينة", "الترتيب الزمني للأحداث"], citation: { documentTitle: title, versionLabel, page: 5, checksumSha256, excerpt: "يدرس المتعلّم الوثيقة التاريخية من حيث طبيعتها، مصدرها، ونوعها." } },
  { id: "history-2am-term-2-national-history", subject: "history", grade: "2am", term: 2, title: "التاريخ الوطني", comprehensiveCompetence, terminalCompetence: "يستغل التوثيق المناسب للوقوف على المحطات الكبرى من تاريخ الجزائر منذ الفتح الإسلامي إلى مواجهة الغزو الإسباني والبرتغالي للمدن الساحلية.", resources: ["الفتح الإسلامي", "المحطات الكبرى في تاريخ الجزائر", "المغرب الإسلامي", "الغزو الإسباني والبرتغالي"], citation: { documentTitle: title, versionLabel, page: 6, checksumSha256, excerpt: "يستغلّ التوثيق المناسب للوقوف على المحطّات الكبرى من تاريخ الجزائر منذ الفتح الإسلامي إلى مواجهة الغزو الاسباني والبرتغالي للمدن الساحلية." } },
  { id: "history-2am-term-3-general-history", subject: "history", grade: "2am", term: 3, title: "التاريخ العام", comprehensiveCompetence, terminalCompetence: "يعتمد خرائط الفتوحات الإسلامية والتوثيق المناسب لإبراز التأثيرات الحضارية الإسلامية في أوروبا والعالم.", resources: ["الدولة الإسلامية", "الفتوحات الإسلامية", "خرائط الامتداد", "التأثيرات الحضارية الإسلامية"], citation: { documentTitle: title, versionLabel, page: 7, checksumSha256, excerpt: "يعتمد خرائط الفتوحـات الإسلاميـة والتوثيـق المناسب لإبراز التأثيرات الحضاريـة الإسلامية في أوربـا والعالـم." } }
];
