-- First detailed daily-notebook sequence from the approved annual plan.
with refs as (select (select id from public.subjects where code='history') as subject_id,(select id from public.grade_levels where code='1am') as grade_id)
insert into public.learning_situations(subject_id,grade_level_id,sort_order,kind,title,competence,resources,suggested_minutes,source_page,source_label)
select subject_id,grade_id,1,'diagnostic','التقويم التشخيصي','استدعاء المكتسبات الضرورية لبناء المقطع','["العصور التاريخية","المعالم التاريخية","خريطة الجزائر"]'::jsonb,5,5,'المخططات السنوية 2022 تاريخ الأولى متوسط' from refs union all
select subject_id,grade_id,2,'launch','الوضعية الانطلاقية: دراسة الآثار','تبرير الحاجة إلى خطوات منهجية لدراسة الآثار وتوظيفها كرونولوجياً','["آثار","كرونولوجيا","نمط معيشة إنسان ما قبل التاريخ"]'::jsonb,5,5,'المخططات السنوية 2022 تاريخ الأولى متوسط' from refs union all
select subject_id,grade_id,3,'learning','الوضعية التعليمية 1: خطوات دراسة الآثار','يتعرف على خطوات منهجية لدراسة الآثار','["الآثار","الخطوات المنهجية"]'::jsonb,55,5,'المخططات السنوية 2022 تاريخ الأولى متوسط' from refs union all
select subject_id,grade_id,4,'partial_integration','إدماج جزئي: مصطلحات الآثار','توظيف المصطلحات المرتبطة بعلم الآثار والتزمين والتنقيب','["عالم الآثار","التزمين","التنقيب"]'::jsonb,20,5,'المخططات السنوية 2022 تاريخ الأولى متوسط' from refs union all
select subject_id,grade_id,5,'learning','الوضعية التعليمية 2: مواقع الآثار وتصنيفها','تصنيف مواقع آثار الإنسان القديم وفق معياري الزمان والمكان','["ما قبل التاريخ","عصور ما قبل التاريخ","المكان والزمان"]'::jsonb,55,5,'المخططات السنوية 2022 تاريخ الأولى متوسط' from refs union all
select subject_id,grade_id,6,'partial_integration','إدماج جزئي: تصنيف الآثار','تصنيف أنواع آثار ما قبل التاريخ في جدول','["الأدوات الحجرية","العظام","النقوش والرسومات"]'::jsonb,20,5,'المخططات السنوية 2022 تاريخ الأولى متوسط' from refs union all
select subject_id,grade_id,7,'learning','الوضعية التعليمية 3: نمط المعيشة والتكيف','ربط المخلفات الأثرية بخصوصية الفترة ونمط معيشة إنسان ما قبل التاريخ','["المخلفات الأثرية","نمط المعيشة","التكيف"]'::jsonb,55,5,'المخططات السنوية 2022 تاريخ الأولى متوسط' from refs union all
select subject_id,grade_id,8,'global_integration','الوضعية الإدماجية: تطور حياة الإنسان','توظيف موارد المقطع لإبراز تطور حياة الإنسان قبل التاريخ','["وثائق أو صور آثار","زيارة افتراضية أو فيديو عند توفره"]'::jsonb,55,5,'المخططات السنوية 2022 تاريخ الأولى متوسط' from refs union all
select subject_id,grade_id,9,'summative_assessment','التقويم التحصيلي للمقطع','تقويم الموارد والكفاءة الختامية للمقطع','["وضعيات بسيطة","وضعية إدماجية"]'::jsonb,55,5,'المخططات السنوية 2022 تاريخ الأولى متوسط' from refs union all
select subject_id,grade_id,10,'remediation','المعالجة البيداغوجية','معالجة صعوبات العد التنازلي وبناء كرونولوجيا العصور القديمة','["خط زمني","بطاقات تاريخية"]'::jsonb,30,5,'المخططات السنوية 2022 تاريخ الأولى متوسط' from refs;
